"""Edit resumes table

Revision ID: 7eefa0e3319a
Revises: 75f0309cb1af
Create Date: 2025-09-01 13:44:06.617759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eefa0e3319a'
down_revision: Union[str, Sequence[str], None] = '75f0309cb1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('content', sa.String(length=1024), nullable=True))
    op.drop_column('resumes', 'compensation')
    op.drop_column('resumes', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('compensation', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('resumes', 'content')
    # ### end Alembic commands ###
